silent-mobs:
  enabled: true
  name: "silence"

anti-enderman-grief:
  enabled: true

no-anvil-limit:
  enabled: true

cauldron-concrete-conversion:
  enabled: true

silk-touch:
  budding-amethyst: false
  reinforced-deepslate: false

baby-mobs:
  enabled: false
  name: "baby"